services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-techchallenge
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: techchallenge
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  techchallenge-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: techchallenge-api
    restart: always
    depends_on:
      - mysql-db
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/app/app.jar"]

volumes:
  mysql_data:
