version: "3.9"

services:

  mysql-db:
    image: mysql:8.0
    container_name: mysql-techchallenge
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: techchallenge
    ports:
      - "3306:3306"
    command: >
      mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

  techchallenge-api:
    build: .
    container_name: techchallenge-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_PROFILES_ACTIVE: prod   # <--- PRODUÇÃO
    command: ["java", "-jar", "/app/app.jar"]

volumes:
  mysql_data:
